image: docker:18.09.7

services:
  - docker:18.09.7-dind


variables:
  REPOSITORY_FRONTEND_SERVICE_URI: {$AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/cloud-develop-demo-frontend-service
  AWS_DEFAULT_OUTPUT: json
  AWS_REGION: us-east-2
  REPO_NAME: cloud-develop-demo-frontend-service

before_script:
  - apk add --no-cache curl jq python py-pip bash
  - pip install awscli
  - echo === Login to Amazon ECR === 
  - aws --version
  
stages:
  - build
  - deploy
  
build frontend:
  stage: build
  script:
    - aws configure set default.region $AWS_REGION
    - aws --profile default configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws --profile default configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws --profile default configure set aws_session_token $AWS_SESSION_TOKEN
    - $(aws ecr get-login --no-include-email --region us-east-2)
    - docker build . -t my-angular-app:latest
    - docker tag my-angular-app:latest $REPOSITORY_FRONTEND_SERVICE_URI:$CI_COMMIT_SHORT_SHA
    - docker push $REPOSITORY_FRONTEND_SERVICE_URI:$CI_COMMIT_SHORT_SHA
deploy dev latest version:
  stage: deploy
  script:
    - chmod +x deployscript.sh
    - aws sts get-caller-identity
    - echo 'Pulling image'
    - IMAGE_TAG=$(aws ecr describe-images --repository-name $REPO_NAME --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --region us-east-2 --output text)
    - echo $IMAGE_TAG
    - ./deployscript.sh $REPO_NAME $REPOSITORY_FRONTEND_SERVICE_URI $IMAGE_TAG
deploy dev specific version:
  stage: deploy
  script:
    - chmod +x deployscript.sh
    - aws sts get-caller-identity
    - echo $IMAGE_TAG
    - ./deployscript.sh $REPO_NAME $REPOSITORY_FRONTEND_SERVICE_URI $IMAGE_TAG
  when: manual